ckpt: null
data_root: /data2/atamkin/DATASETS
gpus: 0

exp:
  base_dir: /mnt/fs2/atamkin/domain-agnostic/models
  name: ???

trainer:
  weights_summary: top
  seed: 0
  val_check_interval: 1.0
  limit_val_batches: 1.0
  precision: 16  # set to 16 for O1 mixed precision
  max_epochs: 100
  gradient_clip_val: 0

optim:
  name: adam
  lr: 0.0001
  weight_decay: 0.0001
  momentum: 0.9  # only used for momentum-based optimizers

defaults:
  - dataset: librispeech_transfer
  - model: transformer  # used to set default model when no ckpt is passed in
